### PR TITLE
fix: improve performance for generating long tones (no array concat)

### PR DESCRIPTION
**Pull request by middi1408**

### CODE REVIEW

**Comment by mo-g** [comment]
This is a really good fix. Borrowed it for my fork along with a couple other tweaks and had a massive performance increase. Generating a 5s sample, I've gone from 2500ms to 3.8ms. Thanks!

**Comment by middi1408** [comment]
I'm glad you could use it! I am generating 30 minute tones and without the performance improvement, I ran out of memory...

**Comment by karlwestin** [comment]
Hey very cool!
(sorry i have not been logged in on this account in a long time)

I merged this on the CLI, so i'll close it here, your commit is in there

I didn't wanna change the return type so i made returning an Int16Array to an option, hope that's ok, thanks a lot!

**Comment by middi1408** [comment]
Hi!

You're welcome!
Sure that's fine of course!

Thanks and best regards,
Michael

**Pull request closed without merging**
